### ISSUE TITLE
[5.0.5] Battle Pet level up alert firing randomly

### ISSUE THREAD

**Issue by SoulCookie** [donniedice/BLU#20]
While playing, I've encountered the sound effect for "Battle Pet Level-Up!" repeatedly, at random times. So far there's no obvious commonality to times that it's sounded, but something appears to be overzealous in finding opportunities for it to trigger. 😄

N.B. AFAIK the addon **is** still working appropriately when my battle pets **do** actually level up. The misfires are happening on top of that, not instead of it.

**Comment by donniedice** [comment]
I found the same bug. Ill work it out today.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by donniedice** [comment]
Alright, up and at-em here. I just pushed **v5.0.6** I _think_ I fixed it?

**Comment by donniedice** [comment]
Ok, v5.0.6 doesn't function properly counter to my thinking. I have v5.0.7 working and will be pushed soon.

**Comment by SoulCookie** [comment]
FWIW, I'm still getting the random pet-level-up sounds in v5.0.7.
